### ISSUE TITLE
Target path miss

### ISSUE THREAD

**Issue by Koc** [mazen/EtcpasswdOAuthBundle#14]
``` yaml
            oauth_vk:
                login_path: /user/auth/form
                check_path: /user/auth-vk/identify
                auth_provider: oauth_vk
                client_id: %vk_client_id%
                client_secret: %vk_client_secret%
                target_path_parameter: redirect_to
                scope: notify,friends,wall
```

open
http://HOSTNAME/user/auth-vk/identify?redirect_to=/places

redirected to 
http://oauth.vk.com/authorize?client_id=2882563&scope=notify,friends,wall&redirect_uri=http%3A%2F%HOSTNAME%2Fuser%2Fauth-vk%2Fidentify&response_type=code

as you see - redirect_to parameter missed
